### ISSUE TITLE
7zip extract issue

### ISSUE THREAD

**Issue by ovidiul** [splitbrain/php-archive#15]
Hi there! I am following a bug reported here https://github.com/ovidiul/XCloner-Wordpress/issues/2 regarding 7zip(I am using your class in a wordpress backup plugin), and it seems for some reason, when adding a directory to the tar archive, it's indicated size is not zero, so maybe it would be a good idea to force the directory size to zero before writing the TAR file headers?

Please see my commit here https://github.com/ovidiul/XCloner-Wordpress/commit/9851d8fb7241023c71bb142271600d0a0444781f , it seems to have fixed the error with 7zip on windows 

Thank you for your time and effort, maybe you can give me some more insight whether there is a need to have a size greater than zero for directories?

**Comment by splitbrain** [comment]
Hmm the problem is probably that filesize() on a directory returns the file system's block size. This of course makes no sense when the directory is stored in an archive and extracted on a possibly different filesystem. So yes, this is a bug.

The proper fix would probably be adjusting the FileInfo class to properly set the filesize to 0 when it's a directory. I look into it later or you could open a pull request.
